name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependancies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc expect

    - name: Compile and check
      run: make check
